version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: akaza-backend
    env_file:
      - /backend/.env
    ports:
      - "8009:8009"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - akaza-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: akaza-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - akaza-network

networks:
  akaza-network:
    driver: bridge